services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: offbeat-api-dev
    ports:
      - '4000:4000'
    env_file: .env

networks:
  default:
    name: coolify
    external: true
