export enum GearCategory {
  CLOTHING = 'CLOTHING',
  FOOTWEAR = 'FOOTWEAR',
  CAMPING = 'CAMPING',
  NAVIGATION = 'NAVIGATION',
  TOILETRIES = 'TOILETRIES',
  DOCUMENTS = 'DOCUMENTS',
  OPTIONAL = 'OPTIONAL',
}
